#!/bin/bash
export LD_LIBRARY_PATH="spot-32/lib"

mkdir temp -p

CREATE_COMMAND="./create_parity_automata-32-nodecomp.sh $1 game"
$CREATE_COMMAND

export PYTHONPATH="$(pwd)/env"
SOLVER_COMMAND="env/bin/python spore.py -gpg -fbdd -dynord automata/game/data.txt"
$SOLVER_COMMAND
RES=$?

if [[ $RES == 10 ]]; then
    echo "REALIZABLE"
elif [[ $RES == 20 ]]; then
    echo "UNREALIZABLE"
else
    echo "UNKNOWN"
fi
